import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ModalController, NavParams, Platform } from '@ionic/angular';
import { TranslateService } from '@ngx-translate/core';
import { MasterService } from 'src/app/services/master.service';

@Component({
  selector: 'app-reportdetalle',
  templateUrl: './reportdetalle.page.html',
  styleUrls: ['./reportdetalle.page.scss'],
})
export class ReportdetallePage implements OnInit {
  @Input() public detalles: any
  @Input() public idEmpresa: any
  @Input() public idGranja: any
  detalle=[{
    id:1,
    pesototal:'',
    CantidadAnimales:'',
    pesoprom:'',
    largo:'',
    alto:'',
    sexo:'',
    especie:null
  }]
  DataForm={
    pesotota:{
      value:''
    },
    cantidadani:{
      value:''
    },
    pesoprom:{
      value:''
    },
    largo:{
      value:''
    },
    alto:{
      value:''
    },
    sexo:{
      value:""
    },
    especie:null
  }
  especies=[]
  ingreso=false;
  update=false;
  numberedit=0;
  idempresas='';
  idGranjas='';
  message=[];
  constructor(private modal:ModalController,private translate:TranslateService,
    navParams: NavParams,private platform:Platform,private master:MasterService,private routr:Router) {
      this.translate.get("modalreportdetalle").subscribe(dataTranslate=>{
        this.message=dataTranslate
       })
      if(navParams.get('detalles')){
        this.detalle=navParams.get('detalles')
      }
      if(navParams.get('idEmpresa')){
        this.idempresas=navParams.get('idEmpresa')
      }
      if(navParams.get('idGranja')){
        this.idGranjas=navParams.get('idGranja')
      }
        this.master.storage.getItems(this.master.storage.arrayname.Especies).then((Especies)=>{
            if(Especies){
                    this.especies=Especies[0]
            }
        })
  }
  changeEspecies(evento){

  }
  borrar(numero){
    console.log(this.detalle.splice(numero,1))
  }
  edit(numero){
    this.DataForm.alto.value=this.detalle[numero].alto
    this.DataForm.cantidadani.value=this.detalle[numero].CantidadAnimales
    this.DataForm.especie=this.detalle[numero].especie
    this.DataForm.largo.value=this.detalle[numero].largo
    this.DataForm.pesoprom.value=this.detalle[numero].pesoprom
    this.DataForm.pesotota.value=this.detalle[numero].pesototal
    this.DataForm.sexo.value=this.detalle[numero].sexo
    this.numberedit=numero
    this.ingreso=true;
    this.update=true;
    this.master.toastMensaje(this.message['editreg'],1000)
  }
  PesoPromedio(){
    if(parseFloat(this.DataForm.pesotota.value)>0 && parseFloat(this.DataForm.cantidadani.value)>0){
      this.DataForm.pesoprom.value=(Math.round(parseFloat(this.DataForm.pesotota.value)/ parseFloat(this.DataForm.cantidadani.value) * 100)/100 ).toString()
    }
  }
  CancelarEdit(){
    this.ingreso=false;
    this.update=false;
    this.numberedit=0;
    let val={
      pesotota:{
        value:''
      },
      cantidadani:{
        value:''
      },
      pesoprom:{
        value:''
      },
      largo:{
        value:''
      },
      alto:{
        value:''
      },
      sexo:{
        value:""
      },
      especie:null
    }
    this.DataForm=val
  }
  finalizarGuardado(){
    this.ingreso=false;
    this.update=false;
    this.numberedit=0;
    let val={
      pesotota:{
        value:''
      },
      cantidadani:{
        value:''
      },
      pesoprom:{
        value:''
      },
      largo:{
        value:''
      },
      alto:{
        value:''
      },
      sexo:{
        value:""
      },
      especie:null
    }
    this.DataForm=val
  }
  continuarGuardado(){
    let val={
      pesotota:{
        value:''
      },
      cantidadani:{
        value:''
      },
      pesoprom:{
        value:''
      },
      largo:{
        value:''
      },
      alto:{
        value:''
      },
      sexo:{
        value:""
      },
      especie:null
    }
    let detal={
      CantidadAnimales:this.DataForm.cantidadani.value,
      alto:this.DataForm.alto.value,
      especie:this.DataForm.especie,
      id:this.detalle.length+1,
      largo:this.DataForm.largo.value,
      pesoprom:this.DataForm.pesoprom.value,
      pesototal:this.DataForm.pesotota.value,
      sexo:this.DataForm.sexo.value
    }
    let valor=this.detalle.push(detal)
    this.DataForm=val
    this.master.toastMensaje(this.message['guardado'],1000)
  }
  ValidarInfo(Edit){
    if(this.DataForm.especie){
      if(this.DataForm.cantidadani.value){
        if(this.DataForm.pesotota.value){
          if(this.DataForm.pesoprom.value){
            if(parseFloat(this.DataForm.cantidadani.value)>=0){
              if(parseFloat(this.DataForm.pesotota.value)>=0){
                if(parseFloat(this.DataForm.pesoprom.value)>=0){
                  if(Edit){
                    this.GrabarEdit()
                  }else{
                    this.continuarGuardado()
                  }
                }else{
                  this.master.MensajeAlert(this.message['validar1'],this.message['validartitul'])
                }
              }else{
                this.master.MensajeAlert(this.message['validar2'],this.message['validartitul'])
              }
            }else{
              this.master.MensajeAlert(this.message['validar3'],this.message['validartitul'])
            }
          }else{
            this.master.MensajeAlert(this.message['validar4'],this.message['validartitul'])
          }
        }else{
          this.master.MensajeAlert(this.message['validar5'],this.message['validartitul'])
        }
      }else{
        this.master.MensajeAlert(this.message['validar6'],this.message['validartitul'])
      }
    }else{
      this.master.MensajeAlert(this.message['validar7'],this.message['validartitul'])
    }
  }
  GrabarEdit(){
    this.detalle[this.numberedit].CantidadAnimales=this.DataForm.cantidadani.value
    this.detalle[this.numberedit].alto=this.DataForm.alto.value
    this.detalle[this.numberedit].especie=this.DataForm.especie
    this.detalle[this.numberedit].largo=this.DataForm.largo.value
    this.detalle[this.numberedit].pesoprom=this.DataForm.pesoprom.value
    this.detalle[this.numberedit].pesototal=this.DataForm.pesotota.value
    this.detalle[this.numberedit].sexo=this.DataForm.sexo.value
    this.ingreso=false;
    this.update=false;
    this.numberedit=0;
    let val={
      pesotota:{
        value:''
      },
      cantidadani:{
        value:''
      },
      pesoprom:{
        value:''
      },
      largo:{
        value:''
      },
      alto:{
        value:''
      },
      sexo:{
        value:""
      },
      especie:null
    }
    this.DataForm=val
  }
  ngOnInit() {
  }
  ionViewWillLeave(){
    this.master.storage.DeleteKey(this.master.storage.arrayname.DetallePrueb).then(()=>{
      this.master.storage.addItem(this.master.storage.arrayname.DetallePrueb,this.detalle).then(()=>{

      })
    })
  }
  finalizar(){
    this.modal.dismiss(this.detalle).then(()=>{
    })
  }
  nuevoingreso(){
    this.ingreso=true;
  }
}
